### ISSUE TITLE
stdout support

### ISSUE THREAD

**Issue by akhenakh** [airspy/host#11]
I've tried to use airspy_rx with "-r -" to be used on the cli (for example pipe to multimon).

Do you plan to support it ?

**Comment by bvernoux** [comment]
It seems f1oat have implemented it here
"airspy_rx can output data on stdout if no output filename is provided" :
https://github.com/f1oat/airspy_host/commit/0ee8703ba8
9792566ec838eae328338e4be64af9

**Comment by martinzsmith** [comment]
If there was a quiet option that sent no output at all to the terminal then the following device could be used (at least under UNIX):
airspy_rx -r /dev/stdout | hexdump -c | head

Or if the stderr was used for all debug output then the following would work:
airspy_rx -r /dev/stdout 2>/dev/null | hexdump -c | head

**Comment by touil** [comment]
Use /dev/stdout.
