### ISSUE TITLE
Verifying that airspy USB works with different USB Hosts

### ISSUE THREAD

**Issue by blort** [airspy/host#13]
The Airspy team has posted a “Use at your own risk” regarding the use of USB 3.0 due to errors in the rtl-sdr library that can cause out of sequence reception of data.

Despite this warning, I've been reading about a lot of people using USB 3.0 ports on their computers and using their ears to verify that the data coming in from the Airspy is:

1) Received at the correct rate

2) The data is not corrupted in anyway.

It seems that some out of sequence data would not be discovered this way.

A better approach would be to add a test mode to the Airspy firmware so it can be commanded to output a known data pattern at a rate the host computer requests it at (320 Mbits / second for 10 Mhz I&Q ...).

I would be willing to write airspy_usb_check if the Airspy team could update the firmware.  Or if you like, I would be willing to update the  firmware as well.  

I’m an experienced software engineer and I can mimic other people’s coding style (I’m doing it with airspy_tcp right now).

Adding this test capability to SDRSharp (far in the future – I know you are super busy) may be worthwhile contemplating as well.

Blort

**Comment by touil** [comment]
The diagnostic tools already support these checks with a very good accuracy. Not to be confused with RTL-SDR. They have nothing in common.
