### ISSUE TITLE
Windows 8.1 airspy_info lists single Aisrpy 32 times.

### ISSUE THREAD

**Issue by martinzsmith** [airspy/host#18]
Problem description see title (or read this for more details https://uk.groups.yahoo.com/neo/groups/airspy/conversations/messages/2013 )

libusb may possibly be the root cause of problem, by returning the same device two times (under Win 8.1) - https://github.com/libusb/libusb/issues/56

Can the airspy_open_device function be modified somehow to workaround this Windows 8.1 libusb bug, at least until libusb put a fix in place for the Windows 8.1 security feature :)
https://github.com/airspy/host/blob/master/libairspy/src/airspy.c#L504

**Comment by bvernoux** [comment]
Thanks for this bug report.
It is clearly a bug of libusb (on Win8.1), I prefer to wait anwer from libusb/libusb#56 maintainer before to try a crappy patch for this case.

**Comment by martinzsmith** [comment]
Sounds like a very reasonable course of action.

**Comment by mcuee** [comment]
I do not see that as a libusb issue (potentially a device issue or driver installation issue) and closed that issue in libusb. You can still reopen the issue if more information are provided to libusb project.

**Comment by bvernoux** [comment]
Problem is personally I do not reproduce this problem and the best will be to discuss it with user reproducing this problem

**Comment by mcuee** [comment]
No problem. If the user does not come back, then you can always close the ticket. In any case, I do not think this is a libusb issue. It could well be a driver installation issue or that user's machine issue.

**Comment by bvernoux** [comment]
Closed this issue cannot be reproduced, can be re-opened if someone find a way to reproduce it.
