### ISSUE TITLE
Airspy, Unitrunker, Windows 8.1 issue

### ISSUE THREAD

**Issue by dsound** [airspy/host#22]
I'm using a Winbook TW100 tablet running Windows 8.1. I'm trying to use Airspy with Unitrunker but am not able to get any signal. Airspy is recognized in UT and I have a working control channel set but when I hit run, there's just a flat line. My R280T works fine. Airspy also works fine in SDR#. Are there any settings in Win8.1 that I should be aware of?

**Comment by bvernoux** [comment]
I'm sorry but your problem is towards Unitrunker and not airspy host tools
You should post & ask question about Unitrunker here
http://www.unitrunker.com/community.html
