### ISSUE TITLE
[1423] closing error

### ISSUE THREAD

**Issue by bibib86** [airspy/host#28]
When I close the program, I get this error.

---------------------------------------------------------------------------------------------------------------------------
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à SDRSharp.MainForm.MainForm_Closing(Object sender, CancelEventArgs e)
   à System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   à System.Windows.Forms.Form.WmClose(Message& m)
   à System.Windows.Forms.Form.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

SDRSharp
    Version de l'assembly : 1.0.0.1423
    Version Win32 : 1.0.0.1423
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.exe

System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

SDRSharp.Radio
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.Radio.DLL

System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34270 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

SDRSharp.Common
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.Common.DLL

SDRSharp.PanView
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.PanView.DLL

System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

SDRSharp.CollapsiblePanel
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.CollapsiblePanel.DLL

SDRSharp.FrequencyEdit
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.FrequencyEdit.DLL

SDRSharp.AIRSPY
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.AIRSPY.DLL

SDRSharp.HackRF
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.HackRF.DLL

SDRSharp.RTLSDR
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.RTLSDR.DLL

SDRSharp.RTLTCP
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.RTLTCP.DLL

SDRSharp.FUNcube
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.FUNcube.DLL

SDRSharp.FUNcubeProPlus
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.FUNcubeProPlus.DLL

SDRSharp.SoftRock
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.SoftRock.DLL

SDRSharp.SDRIQ
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.SDRIQ.DLL

SDRSharp.SDRIP
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.SDRIP.DLL

SDRSharp.AfedriSDRNet
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.AfedriSDRNet.DLL

SDRSharp.IQCorrection
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.IQCorrection.DLL

SDRSharp.NoiseBlanker
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.NoiseBlanker.DLL

SDRSharp.AuxVFO
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.AuxVFO.DLL

SDRSharp.BasebandRecorder
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.BasebandRecorder.DLL

SDRSharp.TimeShift
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.TimeShift.DLL

SDRSharp.DNR
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.DNR.DLL

mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll

SDRSharp.DigitalIfProcessor
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.DigitalIfProcessor.DLL

SDRSharp.DigitalAudioProcessor
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.DigitalAudioProcessor.DLL

SDRSharp.AudioRecorder
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.AudioRecorder.DLL

Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

SDRSharp.DCSDecoder
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.DCSDecoder.DLL

SDRSharp.CTCSSDecoder
    Version de l'assembly : 1.0.0.0
    Version Win32 : 1.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.CTCSSDecoder.DLL

SDRSharp.FrequencyScanner
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.FrequencyScanner.DLL

System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.18408 built by: FX451RTMGREL
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll

Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

SDRSharp.FreqMan
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///C:/Users/Administrateur/Desktop/SDR/sdr-install/sdrsharp/SDRSharp.FreqMan.DLL

Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

**Comment by touil** [comment]
This has nothing to do with libairspy.

**Comment by bibib86** [comment]
Ok....
can be a little help?
since the forum is closed, I do not know where to go ...
