### ISSUE TITLE
Error in lib airspy? Incorrect Sample_Count value in packing mode.

### ISSUE THREAD

**Issue by gssbox** [airspy/host#37]
Good afternoon!

I think I found a bug in the code in LibAirSpy Packing mode on.

When allocating memory:
static int allocate_transfers (airspy_device_t * const device)
{
...
if (device-> packing_enabled)
{
//Error! Invalid considered the number of unpacked samples
// sample_count = ((device-> buffer_size / 2) * 4) / 3; // packed_sample_count = 98304
sample_count =  (((device-> buffer_size / 2) * 4) / 3)/0.75; // unpacked_sample_count = 131072
}
else
{
sample_count = device-> buffer_size / 2;
}
...
}

Also in
static void * consumer_threadproc (void * arg)
{
....

if (device-> packing_enabled)
{
sample_count = ((device-> buffer_size / 2) * 4) / 3; // packed_sample_count = 98304 

if (device-> sample_type! = AIRSPY_SAMPLE_RAW)
{
unpack_samples ((uint32_t *) input_samples, device-> unpacked_samples, sample_count);

input_samples = device-> unpacked_samples;
// Here you need to add a new SampleCount
sample_count = sample_count / 0,75; // unpacked_sample_count = 131072
}
}
else
{
sample_count = device-> buffer_size / 2;
}
....

This is mistake? Or am I wrong understand unpacking operation 12 to 16 bit.

**Comment by touil** [comment]
Make sure you understand the code before filing an issue. This is not a discussion tool.
