### ISSUE TITLE
How to handle more than one device ?

### ISSUE THREAD

**Issue by f4gkr** [airspy/host#39]
Hi AirSpy team,

I am trying to manage more than one device connected on the same computer. Assuming I do not know the serial numbers (hence cannot call airspy_open_sn() ) is there a way to retrieve the list of struct airspy_device* attached ?

Merci
best from F4GKR Sylvain

**Comment by bvernoux** [comment]
The other way to open multiple device without knowing serial number is to call airspy_open() multiple times (without closing the device)
and it will open 1st board found then 2nd board found and so on ... exactly like it is done with [airspy_info.c](https://github.com/airspy/host/blob/master/airspy-tools/src/airspy_info.c#L135) when you do not provide a serial number

**Comment by f4gkr** [comment]
Merci

sylvain

2016-10-09 15:00 GMT+02:00 Benjamin Vernoux <notifications@github.com>:
